update-stack-dev:
	STAGE=dev bash ./update-stack.sh

update-stack-uat:
	STAGE=uat bash ./update-stack.sh

update-stack-prod:
	STAGE=prod bash ./update-stack.sh

update-stack-demo:
	STAGE=demo bash ./update-stack.sh
